### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by LaenExplain** [aaronvincent/captngen#5]
Should we have some automated unit testing?
For example using a python script that can run gencap and transgen on known input (from previous versions) and automatically diff the new results with old results to see if anything could have been unintentionally broken with a change made.

**Comment by patscott** [comment]
Yeah, probably worthwhile.

I would suggest using the GutHub continuous integration system together with Aaron's free GitHub action minutes, and starting off with just a simple run of gentest.  The script should be very simple -- take for example something like this (adapted from the GAMBIT one): 
```yaml
name: capgen CI

on:
  push:
    branches: [ master]
  schedule:
    - cron:  '* * * * 1'

jobs:
  capgen_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ubuntu]
    container: aaronvincent/captngen-base:${{ matrix.arch }}
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        make
    - name: Test
      run: |
        ./gentext.x
    - name: Diff
      run: |
        <do something that diffs the output to required precision with saved output>
```
This just needs to go in a file in the repo `.github/wokflows/ci.yml`.  Possibly one also needs to make some sort of container or something (I am not 100% sure of the `container` line).
